name: Pomodoro
options:
  bundleIdPrefix: com.pomodoro
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

targets:
  Pomodoro:
    type: application
    platform: macOS
    sources:
      - path: Pomodoro
        excludes:
          - Resources/Info.plist
          - Resources/Pomodoro.entitlements
    settings:
      base:
        INFOPLIST_FILE: Pomodoro/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Pomodoro/Resources/Pomodoro.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.pomodoro.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
